USE [master]
GO

/****** Object:  Database [RecordsCountries_Source]    Script Date: 20/9/2023 11:29:43 ******/
CREATE DATABASE [RecordsCountries_Source]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RecordsCountries_Source', FILENAME = N'/var/opt/mssql/data/RecordsCountries_Source.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RecordsCountries_Source_log', FILENAME = N'/var/opt/mssql/data/RecordsCountries_Source_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RecordsCountries_Source].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RecordsCountries_Source] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET ARITHABORT OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RecordsCountries_Source] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RecordsCountries_Source] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RecordsCountries_Source] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RecordsCountries_Source] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET RECOVERY FULL 
GO

ALTER DATABASE [RecordsCountries_Source] SET  MULTI_USER 
GO

ALTER DATABASE [RecordsCountries_Source] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RecordsCountries_Source] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RecordsCountries_Source] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RecordsCountries_Source] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RecordsCountries_Source] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RecordsCountries_Source] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RecordsCountries_Source] SET QUERY_STORE = ON
GO

ALTER DATABASE [RecordsCountries_Source] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [RecordsCountries_Source] SET  READ_WRITE 
GO


USE [RecordsCountries_Source]
GO

/****** Object:  Table [dbo].[OutboxMessages]    Script Date: 20/9/2023 12:06:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OutboxMessages](
	[MessageId] [uniqueidentifier] NOT NULL,
	[CorrelationId] [uniqueidentifier] NOT NULL,
	[CausationId] [uniqueidentifier] NOT NULL,
	[Host] [varchar](255) NULL,
	[Version] [varchar](8) NULL,
	[SavedOn] [datetime] NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[ContentType] [varchar](255) NOT NULL,
	[Error] [nvarchar](max) NULL,
	[Retries] [int] NOT NULL,
	[CreatedOnUtc] [datetime] NOT NULL,
	[ContentId] [varchar](64) NOT NULL,
 CONSTRAINT [PK_OutboxMessages] PRIMARY KEY CLUSTERED 
(
	[MessageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
