version: "3.2"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-server1
    hostname: dddpersons-queue
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest

  redis:
    container_name: redis-server1
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass 1234
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: '0:0'
    container_name: sql-server1
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Abc#123456
      MSSQL_PID: Express

volumes:
  rabbitmqdata: